run_Mode = "None"
ckpt_name = "None"
clipnum = -2
unet_name = "z_image_turbo_bf16.safetensors"
unet_Weight_Dtype = "fp8_e4m3fn"
clip_type = "qwen_image"
clip1 = "qwen_3_4b.safetensors"
clip2 = "None"
guidance = 3.5
clip3 = "None"
clip4 = "None"
vae = "ae.safetensors"
lora = "None"
lora_strength = 1.0
width = 1024
height = 1024
batch = 1
steps = 5
cfg = 1.0
sampler = "euler"
scheduler = "simple"
positive = "beautiful detailed glow,a girl"
negative = "worst quality, low quality"
cache_threshold = "None"
attention = "None"
cpu_offload = "None"
