run_Mode = "None"
ckpt_name = "None"
clipnum = -2
unet_name = "flux-2-klein-4b.safetensors"
unet_Weight_Dtype = "default"
clip_type = "flux2"
clip1 = "qwen_3_4b.safetensors"
clip2 = "None"
guidance = 3.5
clip3 = "None"
clip4 = "None"
vae = "flux2-vae.safetensors"
lora = "None"
lora_strength = 1.0
width = 1024
height = 1024
batch = 1
steps = 4
cfg = 1.0
sampler = "euler"
scheduler = "normal"
positive = "beautiful detailed glow,a girl"
negative = "worst quality, low quality"
cache_threshold = "None"
attention = "None"
cpu_offload = "None"
